version: '3'
services:
  postgresql:
    container_name: 'pgsql'
    image: postgres:16.4
    networks:
      - mynetwork
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data

  php:
    container_name: 'php-fpm-node'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app # Монтируем в общий путь
    depends_on:
      - postgresql
    networks:
      - mynetwork

  nginx:
    container_name: 'nginx'
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./app/src:/usr/share/nginx/html # Nginx будет обслуживать файлы из этой директории
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Подключаем конфигурацию Nginx
    depends_on:
      - php
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
