# Dockerfile.node
FROM node:20

# Установка рабочей директории
WORKDIR /app

# Копирование package.json
COPY package.json ./
COPY package-lock.json ./

# Установка зависимостей из package.json
RUN npm install

# Копирование конфигурационных файлов линтеров в директорию /app
COPY eslint.config.mjs ./
COPY .htmlhintrc ./
COPY .stylelintrc ./

# Копирование остальных файлов приложения
COPY . .